Increase tolerance of test_make_jagged_dedup
Summary:
`test_make_jagged_dedup` fails in some CircleCI jobs (mostly `main`), due to a minor discrepancy:

```
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 224 (0.4%)
Greatest absolute difference: 0.01708984375 at index (0, 16) (up to 0.01 allowed)
Greatest relative difference: 0.03127792672028597 at index (0, 16) (up to 0.01 allowed)
```

The error, probably, accumulates due to the two gemm ops being applied back-to-back in the test. Here we increase the tolerance to `5e-2` to avoid the test failure in CircleCI.

Differential Revision: D44815979

fbshipit-source-id: d87186651c69344bdc20101437564e40a24cb307