Add A10G to detect_target (#279)
Summary:
A10G has compute capability 8.6
AWS instance g5.2xlarge is A10G

Look like we still need to return 80 for A10G.
If `_detect_cuda` returns 86 for A10G then I got - `Arch 86 is not supported by current cutlass lib`. error.
That is  bit strange because cutlas 3.0 (and even 2.11) support arch 8.6 - [doc](https://github.com/NVIDIA/cutlass)
```
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/cuda/target_def.py", line 154, in __enter__
    self._operators = f_gen_ops(self._arch)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/backend/cuda/utils.py", line 60, in gen_ops
    raise NotImplementedError(
NotImplementedError: Arch 86 is not supported by current cutlass lib.
```

Pull Request resolved: https://github.com/facebookincubator/AITemplate/pull/279

Reviewed By: wushirong

Differential Revision: D43414385

Pulled By: chenyang78

fbshipit-source-id: 4e97a7a48201dc2e40098f8fdf92b176a007688d