Fix gap in ads model BF16
Summary:
Now we can set LowerPrecision=BF16 during ads publish pipeline. However, this setting won't change the packaged sample_input's dtype, thus AIT lower pipeline would hit this error during lowering:
```
RuntimeError: AITModel run failed with input spec: [10, 3968]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 64]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 64]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 128]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 64]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 96]:c10::BFloat16, [10, 64]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 120]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 72]:c10::BFloat16, [10, 2069]:c10::BFloat16, [10, 5252]:c10::BFloat16,
```
Because the sample input used by AIT is still fp16. Adding input and submod dtype conversion in pipeline to resolve this issue.
*We cannot add the dtype conversion earlier in pipeline, because this would affect run_on_gpu part of model, which may contain op that doesn't suport BF16.

**TO use BF16 input, AIT lowering setting need to be set as:
(input) precision: LowerPrecision.BF16
output_precision: LowerPrecision.FP16
This setting makes sure the connections between any run_on_acc and run_on_gpu graph is smooth. Otherwise a run_on_gpu graph follow after run_on_acc may throw error due to unable to process BF16 tensors.

Differential Revision: D45298122

fbshipit-source-id: 88aefae6db983b87b89104f256b9a9f5ccb658e2