Make utils init empty to solve circular import issue (#521)
Summary:
If I try to import `aitemplate.utils.misc` in `aitemplate/backend/target.py` then I get the following error:
```
ImportError: cannot import name 'Target' from partially initialized module 'aitemplate.backend.target'
(most likely due to a circular import) (/home/ubuntu/workspace/AITemplate/python/aitemplate/backend/target.py)
```

Internally some `aitemplate.utils` submodules import `aitemplate.compiler` which causes circular import issue above.
To solve the issue we can make `utils.__init__.py` empty to stop importing all `utils` sumbodiles upfront.
It will allow us to use `utils.misc` module in any other modules of the project.

Looks like importing `utils` submodules in the `__init__.py` is not actually required. It will be no negative consequences of making `__init__.py` empty.

Pull Request resolved: https://github.com/facebookincubator/AITemplate/pull/521

Reviewed By: ipiszy

Differential Revision: D44605435

Pulled By: chenyang78

fbshipit-source-id: 5c5af10ad818e82c5286dc8ff08f5cf7384e2dfb